<a href="https://colab.research.google.com/github/seongyeon1/test1/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = tf.Variable(initial_value=0.)

with tf.GradientTape() as tape:
  y = x ** 2 + x * 3 + 14

grad_of_y_wrt_x = tape.gradient(y, x)

In [3]:
grad_of_y_wrt_x.numpy()

3.0

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [7]:
X = tf.Variable(tf.random.uniform((2,2)))

with tf.GradientTape() as tape:
  y = tf.matmul(tf.matmul(X, X), X) + X * 3 + 5

grad_of_t_wrt_x = tape.gradient(y, X)

### Q3 Differentiate $z = X^3 y^2 + 3X + 2xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [5]:
X = tf.Variable(tf.random.uniform((2,2)))
y = tf.Variable(initial_value=0.)

with tf.GradientTape() as tape:
  z = tf.matmul(tf.matmul(X, X), X) * y ** 2 + X * 3 + x * y * 2 + 1

grad_of_z_wrt_X_y = tape.gradient(z, [X, y])

In [6]:
grad_of_z_wrt_X_y

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>]